# Generated by Django 4.1.6 on 2023-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_imageupload_alter_description_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="date_added",
            field=models.DateTimeField(default=True),
        ),
    ]
