# Generated by Django 4.1.4 on 2023-02-25 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UserAccounts", "0001_initial"),
        ("core", "0005_classnotes_remove_description_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=60)),
                ("description", models.TextField(max_length=200)),
                (
                    "upload",
                    models.ImageField(
                        upload_to="notes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("time_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserAccounts.useraccount",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="classnotes", name="topic",),
        migrations.DeleteModel(name="ClassName",),
        migrations.DeleteModel(name="ClassNotes",),
    ]
